---
title: SmartCitizen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@smartcitizen.me
description: The Smart Citizen Kit
baseurl: ""
url: ''
twitter_username: smartcitizenkit
github_username: fablabbcn
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
